/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Gentle Start',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: null,
      targetScore: 100,
      obstacleCount: 2,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Steady Pace',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: null,
      targetScore: 150,
      obstacleCount: 4,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Picking Up Speed',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.4,
      timeLimitSeconds: 60,
      targetScore: 200,
      obstacleCount: 6,
      obstacleSpeed: 0,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Narrowing Paths',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 60,
      targetScore: 300,
      obstacleCount: 8,
      obstacleSpeed: 0,
      collectibleCount: 25,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Treacherous Terrain',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 60,
      targetScore: 400,
      obstacleCount: 10,
      obstacleSpeed: 0,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Treacherous Terrain II',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 60,
      targetScore: 500,
      obstacleCount: 12,
      obstacleSpeed: 0,
      collectibleCount: 35,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Gauntlet of Challenges',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 60,
      targetScore: 600,
      obstacleCount: 15,
      obstacleSpeed: 0,
      collectibleCount: 40,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Perilous Ascent',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 60,
      targetScore: 700,
      obstacleCount: 18,
      obstacleSpeed: 0,
      collectibleCount: 45,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Dizzying Heights',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 60,
      targetScore: 800,
      obstacleCount: 20,
      obstacleSpeed: 0,
      collectibleCount: 50,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Treacherous Summit',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 60,
      targetScore: 900,
      obstacleCount: 25,
      obstacleSpeed: 0,
      collectibleCount: 55,
      collectibleValue: 10,
      backgroundTheme: 'rocky_canyon',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
